### ISSUE TITLE
Latest 0.1.0-alpha.27 cannot be used with npm 9+

### ISSUE THREAD

**Issue by mvanhalen** [lens-protocol/metadata#34]
The latest NPM package has a reference to npm@8+ it gives an error when using it with a newer version of npm please update the reference 9+ seems to be normal combo with nodejs now. .

`npm WARN using --force Recommended protections disabled.
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: @lens-protocol/metadata@0.1.0-alpha.27
npm ERR! notsup Not compatible with your version of node/npm: @lens-protocol/metadata@0.1.0-alpha.27
npm ERR! notsup Required: {"node":"^v18.12.1","pnpm":"^8.0.0","npm":"^8.19.2"}
npm ERR! notsup Actual:   {"npm":"9.5.0","node":"v18.15.0"}`

**Comment by cesarenaldi** [comment]
We don't really need to worry about package managers during install.

Removed altogether here: https://github.com/lens-protocol/metadata/pull/33/commits/ce6064fe655c0eaefe509d48e2fde3c5f9f8ea18

Landing in `alpha.28`.

**Comment by mvanhalen** [comment]
Epic solution!
